services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - proyecto-network

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 40s

  backend-ventas:
    build:
      context: ./back-Ventas_SpringBoot/Springboot-API-REST
    container_name: backend_ventas
    restart: unless-stopped

    ports:
      - "8080:8080"

    env_file:
      - .env

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - proyecto-network

  backend-despachos:
    build:
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    container_name: backend_despachos
    restart: unless-stopped

    ports:
      - "8081:8081"

    env_file:
      - .env

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - proyecto-network

  frontend:
    build:
      context: ./front_despacho
    container_name: frontend_app
    restart: unless-stopped

    ports:
      - "80:80"

    depends_on:
      - backend-ventas
      - backend-despachos

    networks:
      - proyecto-network

volumes:
  mysql_data:

networks:
  proyecto-network:
    driver: bridge