spring.application.name=Springboot-API-REST

# Puerto del backend ventas
server.port=8080

# Configuración de la base de datos MySQL
spring.datasource.url=jdbc:mysql://${DB_ENDPOINT}:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.platform=mysql

# Configuración Hibernate
spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update

# Ejecutar data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
