apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: proyecto-semestral
type: Opaque
stringData:
  DB_USERNAME: "admin"
  DB_PASSWORD: "admin123"
  MYSQL_ROOT_PASSWORD: "123456"
  MYSQL_USER: "admin"
  MYSQL_PASSWORD: "admin123"
  